<?php

/**
 * Mail Class
 *
 * @author Jaco Ruit
 */
class Mail {
    /**
     * Sends an email
     * @param array   $paramEmailArray Array generated by MailFactory
     * @param boolean $paramSendHeaders Indicating if headers have to be send
     * @return boolean Indicating if the email was sent
     */
    public static function sendEmail($paramEmailArray, $paramSendHeaders){ 
        if($paramSendHeaders){
            echo $paramHeaders;
            return mail($paramEmailArray['to'], $paramEmailArray['subject'], $paramEmailArray['headers']);
            
        }
        else{
            return mail($paramEmailArray['to'], $paramEmailArray['subject']);
        }
    }
}

?>
